##############################################################
##############################################################
##### SCRIPT TO ESTIMATE CATCH RATE BY AREA BY  WEEKNR OF SHRIMPS
#####          based on script toanalyse 
#####          EFFORT - LANDINGS ANALYSE PULSVLOOT voor WGELECTRA
#####  adriaan rijnsdorp: april 2018
##############################################################
##############################################################
## input data sets generated by Jacco van Rijssel March 2018 
## data set of all effort and landings reported by week (fishing trip)
###############
## Corrections: SL3, SCH63 added as these were erroneously excluded from previous analysis
##############################################################
# load("W:/IMARES/IJmuiden/Afdeling/Projecten/Pulsvisserij/2018/pulsefficiency/results/Pulseornopulseincl20178species.Rdata")
##############
load("D:/Adriaan/Onderzoek/Data/Effort/Effort_Pulse/Pulseornopulseincl20178species.Rdata")
names(tripinfo)
# [1] "VE_REF"      "year"        "weeknr"      "FT_REF"      "VE_KW"       "LE_RECT"     "month"       "ldate"       "eff"        
# [10] "FT_LDAT"     "LE_MET"      "LE_GEAR"     "LE_KG_PLE"   "LE_KG_SOL"   "LE_KG_COD"   "LE_KG_WHG"   "LE_KG_MUR"   "LE_KG_NEP"  
# [19] "LE_KG_CSH"   "LE_KG_BSS"   "LE_KG_TOT"   "info"        "mu1"         "mu2"         "mu3"         "doy"         "date"       
# [28] "pulse"       "loess3"      "loess2"      "geargood"    "sumcrus"     "sumall"      "perccrus"    "percshrimp"  "percsole"   
# [37] "percplaice"  "sumflat"     "percflat"    "effortsplit"
unique(tripinfo$LE_MET)
# [1] "TBB_DEF_70-99_0_0"   "OTB_DEF_100-119_0_0" "OTB_DEF_UND_0_0"     "OTB_DEF_70-99_0_0"   "TBB_DEF_16-31_0_0"  
# [6] "TBB_DEF_100-119_0_0" "TBB_DEF_UND_0_0"     "TBB_DEF_>=120_0_0"   "TBB_DEF_90-119_0_0"  "OTB_DEF_<16_0_0"    
# [11] "TBS_CRU_16-31_0_0"   "OTB_MCD_>0_0_0"      "OTB_DEF_>=120_0_0"   "OTB_MCD_70-99_0_0"   "SUM_UND_70-99_0_0"  
# [16] "SUM_UND_>=120_0_0"   "LHP_FIF_0_0_0"       "OTB_DEF_16-31_0_0"   "RG_UND_UND_0_0"      "SSC_DEF_70-99_0_0"  
# [21] "SSC_DEF_100-119_0_0" "SUM_UND_100-119_0_0" "OTG_UND_UND_0_0"     "OTM_SPF_70-99_0_0"   "OTT_MCD_70-99_0_0"  
# [26] "OTT_DEF_70-99_0_0"   "GNS_DEF_UND_0_0"     "GNS_DEF_90-99_0_0"   "GNS_DEF_120-219_0_0" "GNS_DEF_100-119_0_0"
# [31] "LHM_FIF_0_0_0"       "TBB_DEF_<16_0_0"     "HMD_MOL_0_0_0"       "HMD_MOL_UND_0_0"     "MIS_UND_UND_0_0"    
# [36] "HMD_MOL_<16_0_0"     "DRB_MOL_0_0_0"       "HMD_MOL_70-99_0_0"   "SUM_UND_UND_0_0"     "TBS_CRU_<16_0_0"    
# [41] "OTB_MCD_100-119_0_0" "QUA_UND_70-99_0_0"   "QUA_MCD_70-99_0_0"   "QUA_UND_16-31_0_0"   "TBB_MCD_16-31_0_0"  
# [46] "OTB_DEF_0_0_0"       "TBB_MCD_70-99_0_0"   "OTT_DEF_100-119_0_0" "OTT_MCD_100-119_0_0" "GTR_DEF_120-219_0_0"
# [51] "GNS_DEF_10-30_0_0"   "HMD_MOL_>=120_0_0"   "FPO_CRU_UND_0_0"     "OTM_SPF_32-69_0_0"   "OTM_SPF_32-54_0_0"  
# [56] "OTM_SPF_UND_0_0"     "OTM_SPF_<16_0_0"     "OTM_SPF_16-31_0_0"   "OTM_SPF_>=120_0_0"   "OTT_DEF_>=120_0_0"  
# [61] "OTT_DEF_90-119_0_0"  "GTR_DEF_10-30_0_0"   "PTM_SPF_32-69_0_0"   "PTM_SPF_16-31_0_0"   "PTM_SPF_32-54_0_0"  
# [66] "OTB_DEF_32-69_0_0"   "OTM_SPF_100-119_0_0" "SDN_DEF_>0_0_0"      "SDN_DEF_70-99_0_0"   "SDN_DEF_100-119_0_0"
# [71] "SDN_DEF_>=120_0_0"   "SSC_DEF_>=120_0_0"   "OTM_SPF_55-69_0_0"   "SSC_DEF_UND_0_0"     "SSC_DEF_>=70_0_0"   
# [76] "SSC_DEF_32-69_0_0"   "PTM_SPF_100-119_0_0" "FPO_CRU_0_0_0"       "OTT_DEF_>0_0_0"      "SUM_UND_90-119_0_0" 
# [81] "AG_UND_UND_0_0"      "SSC_DEF_90-119_0_0"  "PTB_DEF_>=120_0_0"   "OTB_DEF_90-119_0_0"  "FPO_CRU_10-30_0_0"  
# [86] "OTT_MCD_>=120_0_0"   "OTB_MCD_UND_0_0"     "TBB_DEF_70-89_0_0"   "SSC_DEF_0_0_0"       "PTB_MCD_70-99_0_0"  
# [91] "OTB_MCD_>=120_0_0"   "TBB_MCD_>=120_0_0"   "OTB_MCD_<16_0_0"     "OTT_MCD_<16_0_0"     "PTB_DEF_70-99_0_0"  
# [96] "No_logbook6"         "OTT_DEF_16-31_0_0"   "OTT_MCD_UND_0_0"     "GNS_MCD_120-219_0_0" "GNS_MCD_100-119_0_0"
# [101] "TBB_MCD_100-119_0_0" "QUA_MCD_100-119_0_0" "GNS_DEF_50-70_0_0"   "TBB_DEF_32-69_0_0"   "PTB_DEF_16-31_0_0"  
unique(tripinfo$VE_REF)
# [1] "ARM14"  "ARM15"  "ARM18"  "ARM20"  "ARM22"  "ARM25"  "ARM33"  "ARM4"   "ARM44"  "ARM46"  "ARM7"   "BR10"  
# [13] "BR14"   "BR29"   "BR43"   "BR7"    "GO1"    "GO14"   "GO20"   "GO22"   "GO23"   "GO26"   "GO27"   "GO28"  
# [25] "GO29"   "GO31"   "GO32"   "GO33"   "GO37"   "GO38"   "GO4"    "GO44"   "GO48"   "GO5"    "GO55"   "GO57"  
# [37] "GO58"   "GO59"   "GO6"    "GO8"    "GO9"    "HA106"  "HA13"   "HA18"   "HA31"   "HA36"   "HA4"    "HA43"  
# [49] "HA5"    "HA61"   "HA75"   "HA76"   "HA8"    "HD16"   "HD22"   "HD222"  "HD27"   "HD29"   "HD3"    "HD30"  
# [61] "HD32"   "HD36"   "HD4"    "HD42"   "HD5"    "HD64"   "HD65"   "HD70"   "HD9"    "HD96"   "HK81"   "IJM18" 
# [73] "IJM31"  "IJM8"   "KG18"   "KG8"    "KG9"    "KW145"  "KW170"  "KW172"  "KW174"  "KW34"   "KW43"   "KW45"  
# [85] "KW5"    "KW72"   "KW88"   "LE62"   "LE63"   "LO137"  "LO17"   "LO28"   "LO44"   "LO7"    "LO8"    "MDV1"  
# [97] "OD1"    "OD3"    "OD5"    "OD50"   "OD6"    "OD7"    "OD9"    "OL12"   "OL37"   "SCH10"  "SCH118" "SCH123"
# [109] "SCH135" "SCH18"  "SCH22"  "SCH23"  "SCH24"  "SCH27"  "SCH302" "SCH303" "SCH333" "SCH42"  "SCH45"  "SCH54" 
# [121] "SCH6"   "SCH63"  "SCH65"  "SCH72"  "SCH81"  "SL27"   "SL3"    "SL42"   "SL9"    "ST24"   "ST25"   "ST4"   
# [133] "TH10"   "TH119"  "TH43"   "TH5"    "TH6"    "TH7"    "TM19"   "TX1"    "TX10"   "TX14"   "TX19"   "TX21"  
# [145] "TX25"   "TX27"   "TX29"   "TX3"    "TX33"   "TX35"   "TX36"   "TX38"   "TX41"   "TX43"   "TX48"   "TX65"  
# [157] "TX68"   "TX94"   "UK1"    "UK112"  "UK135"  "UK137"  "UK143"  "UK145"  "UK149"  "UK151"  "UK152"  "UK153" 
# [169] "UK155"  "UK156"  "UK158"  "UK16"   "UK161"  "UK162"  "UK163"  "UK165"  "UK166"  "UK167"  "UK170"  "UK171" 
# [181] "UK172"  "UK176"  "UK177"  "UK179"  "UK184"  "UK19"   "UK190"  "UK194"  "UK195"  "UK197"  "UK2"    "UK200" 
# [193] "UK210"  "UK22"   "UK224"  "UK227"  "UK23"   "UK236"  "UK237"  "UK24"   "UK242"  "UK243"  "UK244"  "UK246" 
# [205] "UK253"  "UK266"  "UK268"  "UK271"  "UK272"  "UK274"  "UK284"  "UK287"  "UK292"  "UK307"  "UK317"  "UK33"  
# [217] "UK34"   "UK368"  "UK37"   "UK382"  "UK44"   "UK45"   "UK456"  "UK47"   "UK48"   "UK5"    "UK53"   "UK56"  
# [229] "UK57"   "UK61"   "UK64"   "UK71"   "UK73"   "UK80"   "UK87"   "UK88"   "UK92"   "UK94"   "UK95"   "UQ15"  
# [241] "UQ17"   "UQ18"   "UQ21"   "VD6"    "VD77"   "VLI25"  "VLI27"  "VLI28"  "VLI5"   "VLI7"   "WL15"   "WL18"  
# [253] "WL23"   "WL28"   "WL3"    "WL33"   "WL39"   "WL4"    "WL8"    "WON17"  "WON43"  "WR106"  "WR108"  "WR109" 
# [265] "WR111"  "WR112"  "WR115"  "WR12"   "WR122"  "WR123"  "WR124"  "WR126"  "WR129"  "WR130"  "WR160"  "WR17"  
# [277] "WR18"   "WR181"  "WR189"  "WR19"   "WR2"    "WR20"   "WR21"   "WR212"  "WR213"  "WR22"   "WR222"  "WR23"  
# [289] "WR230"  "WR244"  "WR27"   "WR274"  "WR29"   "WR291"  "WR3"    "WR36"   "WR389"  "WR40"   "WR42"   "WR50"  
# [301] "WR52"   "WR54"   "WR57"   "WR67"   "WR68"   "WR7"    "WR71"   "WR8"    "WR88"   "WR89"   "WR9"    "WR98"  
# [313] "YE118"  "YE137"  "YE138"  "YE139"  "YE238"  "YE243"  "YE6"    "YE63"   "YE76"   "YE88"   "ZK10"   "ZK12"  
# [325] "ZK13"   "ZK14"   "ZK17"   "ZK185"  "ZK2"    "ZK21"   "ZK40"   "ZK43"   "ZK44"   "ZK48"   "ZK49"   "ZK65"  
# [337] "ZK67"   "ZK8"    "ZK80"   "ZK81"   "ZK87"   "ZK92"  

# select <- read.csv("M:\\My documents\\Adriaan\\Projecten\\2018_PulseTrawl\\R_2018_June\\SelectPulsVessels.csv")
# colnames(select) <- c("VE_REF","Puls_ID","Engine_Class","Start_date")
########################################################
###  Collapse data set to 1 record per landing date (multiple trips possible within a week)
###  tmp.eff contains effort per landing date and vessel
########################################################
tmp.eff <- unique(tripinfo[,c(1,2,3,8,9)])
names(tmp.eff)
# [1] "VE_REF" "FT_REF" "ldate"  "eff"  
###
dat <- tripinfo
########################################################
###  Calculate sum landings by species by landing date and vessel
########################################################
tmp <- aggregate(LE_KG_PLE ~ VE_REF+ldate,data=dat,FUN=sum)
tmp.sol <- aggregate(LE_KG_SOL ~ VE_REF+ldate,data=dat,FUN=sum)
tmp.cod <- aggregate(LE_KG_COD ~ VE_REF+ldate,data=dat,FUN=sum)
tmp.whg <- aggregate(LE_KG_WHG ~ VE_REF+ldate,data=dat,FUN=sum)
tmp.mur <- aggregate(LE_KG_MUR ~ VE_REF+ldate,data=dat,FUN=sum)
tmp.nep <- aggregate(LE_KG_NEP ~ VE_REF+ldate,data=dat,FUN=sum)
tmp.csh <- aggregate(LE_KG_CSH ~ VE_REF+ldate,data=dat,FUN=sum)
tmp.bss <- aggregate(LE_KG_BSS ~ VE_REF+ldate,data=dat,FUN=sum)
tmp.tot <- aggregate(LE_KG_TOT ~ VE_REF+ldate,data=dat,FUN=sum)

tmp$sol <- tmp.sol$LE_KG_SOL
tmp$cod <- tmp.cod$LE_KG_COD
tmp$whg <- tmp.whg$LE_KG_WHG
tmp$mur <- tmp.mur$LE_KG_MUR
tmp$nep <- tmp.nep$LE_KG_NEP
tmp$csh <- tmp.csh$LE_KG_CSH
tmp$bss <- tmp.bss$LE_KG_BSS
tmp$tot <- tmp.tot$LE_KG_TOT
colnames(tmp) <- c("VE_REF","ldate","ple","sol","cod","whg","mur","nep","csh","bss","tot")
##########################################################################
##########################################################################
### now determine the ICES RECTANGLE with the highest landings (sumall) per trip
### and remove the 2nd record (lowest landings)
### keep relevant variables for each trip
### merge data set with the summed landings by species by trip
##########################################################################
tmp1 <- tripinfo[order(tripinfo$FT_REF,tripinfo$LE_KG_TOT,decreasing = TRUE),c(1:12,23:28,31)]
tmp2 <- tmp1[!duplicated(tmp1$FT_REF),]
tmp3 <- merge(tmp,tmp2,by=c("VE_REF","ldate"),all=T)
names(tmp3)
# [1] "VE_REF"   "ldate"    "ple"      "sol"      "cod"      "whg"      "mur"      "nep"     
# [9] "csh"      "bss"      "tot"      "year"     "weeknr"   "FT_REF"   "VE_KW"    "LE_RECT" 
# [17] "month"    "eff"      "FT_LDAT"  "LE_MET"   "LE_GEAR"  "mu1"      "mu2"      "mu3"     
# [25] "doy"      "date"     "pulse"    "geargood"
##########################################################################
dat1 <- tmp3[tmp3$LE_MET=="TBB_DEF_16-31_0_0" | tmp3$LE_MET=="TBS_CRU_16-31_0_0",]
##########################################################################
dat1$area <- NA
area01 <- c("31F1","32F1","33F1")
area02 <- c("31F2","31F3","32F3","32F4","33F4","34F4")
area03 <- c("32F2","33F2","34F2","33F3","34F3")
area04 <- c("35F0","35F1","36F0","36F1","37E9","37F0","38E8","38E9","38F0")
area05 <- c("35F2","35F3","36F2","36F3","36F4","37F3","37F4","38F4")
area06 <- c("35F4","35F5","36F5","36F6","36F7","36F8")
area07 <- c("37F7","37F8","38F7","38F8")
area08 <- c("39F7","39F8","40F7","40F8")
area09 <- c("41F7","41F8","42F7","42F8")
area10 <- c("37F5","37F6","38F5","38F6")
area11 <- c("39F5","39F6","40F5","40F6")
area12 <- c("41F5","41F6","42F5","42F6","43F5")
area13 <- c("37F1","37F2","38F1","38F2","38F3")
area14 <- c("39F2","39F3","39F4","40F4")
area16 <- c(
  "45E7","45E8","45E9","45F0","45F1","45F2","45F3","45F4",
  "44E7","44E8","44E9","44F0","44F1","44F2","44F3","44F4",
  "43E7","43E8","43E9","43F0","43F1","43F2","43F3","43F4",
  "42E7","42E8","42E9","42F0","42F1","42F2","42F3","42F4",
  "41E7","41E8","41E9","41F0","41F1","41F2","41F3","41F4",
  "40E7","40E8","40E9","40F0","40F1","40F2","40F3","40F4",
  "39E8","39E9","39F0","39F1")
############################
dat1$area[dat1$LE_RECT %in% area01] <- 1
dat1$area[dat1$LE_RECT %in% area02] <- 2
dat1$area[dat1$LE_RECT %in% area03] <- 3
dat1$area[dat1$LE_RECT %in% area04] <- 4
dat1$area[dat1$LE_RECT %in% area05] <- 5
dat1$area[dat1$LE_RECT %in% area06] <- 6
dat1$area[dat1$LE_RECT %in% area07] <- 7
dat1$area[dat1$LE_RECT %in% area08] <- 8
dat1$area[dat1$LE_RECT %in% area09] <- 9
dat1$area[dat1$LE_RECT %in% area10] <- 10
dat1$area[dat1$LE_RECT %in% area11] <- 11
dat1$area[dat1$LE_RECT %in% area12] <- 12
dat1$area[dat1$LE_RECT %in% area13] <- 13
dat1$area[dat1$LE_RECT %in% area14] <- 14
dat1$area[dat1$LE_RECT %in% area16] <- 16
############################
dat <- dat1[dat1$csh>0,c(1,2,9,12,13,15,16,18,29)]
dat$cpue.csh <- dat$csh/dat$eff
aggregate(cpue.csh~area,data=dat,FUN=mean)
aggregate(cpue.csh~area,data=dat,FUN=length)
# area cpue.csh
# 1     1        3
# 2     2    13500
# 3     3      403
# 4     4        2
# 5     5      147
# 6     6    23559
# 7     7     5262
# 8     8     1045
# 9     9        2
# 10   10       80
# 11   11        8
# 12   13        8
# 13   14        6
# 14   16        6
## select only coastal areas 2,6,7,8
select <- c(2,6,7,8)
dat1 <- dat[dat$area %in% select,]
#################################################################################
###
###  GAMM ANALYSE TIME TRENDS IN CPUE BY AREA (SOUTHERN NORTH SEA)
###
#################################################################################
#################################################################################
require("mgcv")
# dat$decimal.year <- dat$year+dat$weeknr/53-1/53
# dat$time.week <- (dat$year-2009)*52+dat$weeknr
# y2 <- as.POSIXlt(dat$ldate)
# y1 <- as.POSIXlt("2009-01-01")
# dat$time.day <- floor(y2-y1)
dat1$lcpue <- log(dat1$cpue.csh)
dat1$cpue <- (dat1$cpue.csh)
# m1 <- gamm(cpue ~  as.factor(area) + as.factor(year) + 
#              + s(weeknr, by=as.factor(area), k=20),
#            random=list(VE_REF=~1),method="REML",
#            data = dat1, 
#            family="quasipoisson")
# #plot(m.sol$gam,all.terms=T)
# summary(m1$lme)
# m2 <- gam(cpue ~  as.factor(area) + as.factor(year) + 
#             + s(weeknr, by=as.factor(area), k=20), method="REML",
#           data = dat1, 
#           family="quasipoisson")
# #plot(m.sol$gam,all.terms=T)
# summary(m1$lme)
#########################################
### neg binoial
m2 <- gam(cpue ~  as.factor(area) + as.factor(year) + 
            + s(weeknr, bs=c("cc"), by=as.factor(area)), method="REML",
          data = dat1, 
          family=negbin(1))
m3 <- gam(cpue ~  as.factor(area) + as.factor(year) + 
            + s(weeknr, bs=c("cc"), by=as.factor(area), k=20), method="REML",
          data = dat1, 
          family=negbin(1))
m4 <- gam(cpue ~  as.factor(area) + as.factor(year) + 
            + te(weeknr, bs=c("cc"), by=as.factor(area), k=10), method="REML",
          data = dat1, 
          family=negbin(1))
#plot(m.sol$gam,all.terms=T)
AIC(m2,m3,m4)
# df      AIC
# m2 38.99544 401978.8
# m3 60.22743 401602.5  <----
# m4 38.99544 401978.8
##########################################
## predict catch rates by area by week
tmp1 <- rep(c(2,6,7,8),each=52)
tmp2 <- rep(c(1:52),4)
ndata <- data.frame(weeknr=tmp2,area=tmp1)
ndata$year <- 2016
#pred1 <- predict(m3,pred,type="response",se.fit=TRUE)
pred <- predict(m3,ndata,type="link",se.fit=TRUE)
ndata$fit <- exp(pred$fit)
ndata$lower <- exp(pred$fit-1.96*pred$se.fit)
ndata$upper <- exp(pred$fit+1.96*pred$se.fit)
write.csv(ndata,"M:\\My Documents\\Adriaan\\Projecten\\2018_DSVM_pulse_tbb\\cpue_csh.csv")
